#!/usr/bin/env python3
"""Generates the adaptive launcher icons from the bundled medal art.

For every medal in app/src/main/assets/dota_rank_medals.json this writes a foreground
and a monochrome (themed icon) vector with the medal as Glyph Matrix dots, plus the
adaptive icon that combines them. Run it again after changing the medal art:

    python3 tools/make_icons.py
"""
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main")
ROW_WIDTHS = [7, 11, 15, 17, 19, 21, 21, 23, 23, 25, 25, 25, 25, 25, 25, 25, 23, 23, 21, 21, 19, 17, 15, 11, 7]
SIZE = 25
VIEWPORT = 108.0   # adaptive icon canvas (dp)
SPAN = 64.0        # the matrix fits the 66 dp safe zone
CELL = SPAN / SIZE
DOT_RADIUS = CELL * 0.42
LEVELS = 8         # grey levels, one path each
UNLIT = "#FF1E1E1E"


def is_led(x, y):
    start = (SIZE - ROW_WIDTHS[y]) // 2
    return start <= x < start + ROW_WIDTHS[y]


def dot(x, y):
    left = (VIEWPORT - SPAN) / 2
    cx = left + (x + 0.5) * CELL
    cy = left + (y + 0.5) * CELL
    r = DOT_RADIUS
    return f"M{cx - r:.2f},{cy:.2f}a{r:.2f},{r:.2f} 0,1 1,{2 * r:.2f},0a{r:.2f},{r:.2f} 0,1 1,{-2 * r:.2f},0z"


def level_of(v):
    return 0 if v < 16 else min(LEVELS, 1 + v * LEVELS // 256)


def vector(paths, comment):
    body = "\n".join(
        f'    <path android:fillColor="{color}" android:pathData="{"".join(data)}"/>' for color, data in paths if data
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {comment} Generated by tools/make_icons.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
{body}
</vector>
"""


def main():
    art = json.load(open(os.path.join(ROOT, "assets", "dota_rank_medals.json")))["ranks"]
    drawable = os.path.join(ROOT, "res", "drawable")
    mipmap = os.path.join(ROOT, "res", "mipmap-anydpi")
    os.makedirs(mipmap, exist_ok=True)
    for key, rows in art.items():
        levels = {lvl: [] for lvl in range(LEVELS + 1)}
        for y in range(SIZE):
            for x in range(SIZE):
                if is_led(x, y):
                    levels[level_of(rows[y][x])].append(dot(x, y))
        grey = lambda lvl: "#FF" + f"{round(255 * lvl / LEVELS):02X}" * 3
        fg = [(UNLIT, levels[0])] + [(grey(l), levels[l]) for l in range(1, LEVELS + 1)]
        mono = [("#" + f"{round(255 * l / LEVELS):02X}" + "FFFFFF", levels[l]) for l in range(1, LEVELS + 1)]
        with open(os.path.join(drawable, f"ic_medal_{key}.xml"), "w") as f:
            f.write(vector(fg, f"{key.title()} medal on the Glyph Matrix, launcher icon foreground."))
        with open(os.path.join(drawable, f"ic_medal_{key}_mono.xml"), "w") as f:
            f.write(vector(mono, f"{key.title()} medal, themed (monochrome) launcher icon."))
        # The Immortal medal is the default icon (ic_launcher); it is also used while uncalibrated.
        name = "ic_launcher" if key == "immortal" else f"ic_launcher_{key}"
        with open(os.path.join(mipmap, f"{name}.xml"), "w") as f:
            f.write(f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_icons.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_medal_{key}" />
    <monochrome android:drawable="@drawable/ic_medal_{key}_mono" />
</adaptive-icon>
""")
    print("wrote icons for", ", ".join(art))


if __name__ == "__main__":
    main()
